name: open_weather
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_spinkit: "^4.1.2"
  http: ^0.12.1
  geolocator: ^6.1.2
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - ./lib/assets/images/backgrounds/
